// Package observerstore persists only operational observer metadata. It never
// stores JSONL lines, transcript content, tool arguments, or tool output.
package observerstore

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	_ "modernc.org/sqlite"
)

// FileMetadata is deliberately limited to resumable tailing metadata. FileID
// and LastEventFingerprint are SHA-256 values generated by codexobserver.
type FileMetadata struct {
	FileID               string
	SessionID            string
	CommittedOffset      int64
	LastEventFingerprint string
}

type Store struct {
	mu sync.Mutex
	db *sql.DB
}

func Open(path string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, fmt.Errorf("create observer metadata directory: %w", err)
	}
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("open observer metadata: %w", err)
	}
	store := &Store{db: db}
	if err := store.initialize(); err != nil {
		_ = db.Close()
		return nil, err
	}
	return store, nil
}

func (s *Store) initialize() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`
		PRAGMA journal_mode=WAL;
		CREATE TABLE IF NOT EXISTS observed_files (
			file_id TEXT PRIMARY KEY,
			session_id TEXT NOT NULL DEFAULT '',
			committed_offset INTEGER NOT NULL,
			last_event_fingerprint TEXT NOT NULL DEFAULT '',
			updated_at TEXT NOT NULL
		);
		CREATE TABLE IF NOT EXISTS managed_processes (
			session_id TEXT PRIMARY KEY,
			pid INTEGER NOT NULL,
			started_at TEXT NOT NULL
		);
		CREATE TABLE IF NOT EXISTS session_continuations (
			source_session_id TEXT PRIMARY KEY,
			parent_session_id TEXT NOT NULL,
			created_at TEXT NOT NULL
		);
	`)
	if err != nil {
		return fmt.Errorf("initialize observer metadata: %w", err)
	}
	// A previous Connector process no longer owns an interactive PTY after a
	// restart. Do not ever expose its PID as remotely controllable.
	_, err = s.db.Exec(`DELETE FROM managed_processes`)
	if err != nil {
		return fmt.Errorf("reset stale managed processes: %w", err)
	}
	return nil
}

func (s *Store) SaveContinuation(sourceSessionID, parentSessionID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`
		INSERT INTO session_continuations (source_session_id, parent_session_id, created_at)
		VALUES (?, ?, ?)
		ON CONFLICT(source_session_id) DO UPDATE SET
			parent_session_id = excluded.parent_session_id,
			created_at = excluded.created_at
	`, sourceSessionID, parentSessionID, time.Now().UTC().Format(time.RFC3339Nano))
	if err != nil {
		return fmt.Errorf("save session continuation: %w", err)
	}
	return nil
}

func (s *Store) ContinuationParent(sourceSessionID string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	var parentSessionID string
	err := s.db.QueryRow(`SELECT parent_session_id FROM session_continuations WHERE source_session_id = ?`, sourceSessionID).Scan(&parentSessionID)
	if err == sql.ErrNoRows {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("read session continuation: %w", err)
	}
	return parentSessionID, nil
}

func (s *Store) DeleteContinuation(sourceSessionID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`DELETE FROM session_continuations WHERE source_session_id = ?`, sourceSessionID)
	if err != nil {
		return fmt.Errorf("delete session continuation: %w", err)
	}
	return nil
}

func (s *Store) SaveFile(value FileMetadata) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`
		INSERT INTO observed_files (file_id, session_id, committed_offset, last_event_fingerprint, updated_at)
		VALUES (?, ?, ?, ?, ?)
		ON CONFLICT(file_id) DO UPDATE SET
			session_id = excluded.session_id,
			committed_offset = excluded.committed_offset,
			last_event_fingerprint = excluded.last_event_fingerprint,
			updated_at = excluded.updated_at
	`, value.FileID, value.SessionID, value.CommittedOffset, value.LastEventFingerprint, time.Now().UTC().Format(time.RFC3339Nano))
	if err != nil {
		return fmt.Errorf("save observer file metadata: %w", err)
	}
	return nil
}

func (s *Store) DeleteFile(fileID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`DELETE FROM observed_files WHERE file_id = ?`, fileID)
	if err != nil {
		return fmt.Errorf("delete observer file metadata: %w", err)
	}
	return nil
}

func (s *Store) SaveManagedProcess(sessionID string, pid int, startedAt string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`
		INSERT INTO managed_processes (session_id, pid, started_at) VALUES (?, ?, ?)
		ON CONFLICT(session_id) DO UPDATE SET pid = excluded.pid, started_at = excluded.started_at
	`, sessionID, pid, startedAt)
	if err != nil {
		return fmt.Errorf("save managed process metadata: %w", err)
	}
	return nil
}

func (s *Store) DeleteManagedProcess(sessionID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, err := s.db.Exec(`DELETE FROM managed_processes WHERE session_id = ?`, sessionID)
	if err != nil {
		return fmt.Errorf("delete managed process metadata: %w", err)
	}
	return nil
}

func (s *Store) Close() error {
	if s == nil || s.db == nil {
		return nil
	}
	return s.db.Close()
}
